M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Fri Jul 24 16:54:44 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-24T16:54:44+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X130.11Y-105.005
X135.89Y-105.005
T2
X103.5Y-103.5
X103.5Y-134.5
X154.5Y-103.5
X154.5Y-134.5
M30
